import time
import os
delay = int(input("enter delay time"))
repeattimes = int(input("how many repeats"))
# Not the cleanest but it does the thing
for x in range(0,repeattimes):
    print("o")
    time.sleep(delay)
    os.system('cls')
    print(" o")
    time.sleep(delay)
    os.system('cls')
    print("  o")
    time.sleep(delay)
    os.system('cls')
    print("   o")
    time.sleep(delay)
    os.system('cls')
    print("    o")
    time.sleep(delay)
    os.system('cls')
    print("     o")
    time.sleep(delay)
    os.system('cls')
    print("      o")
    time.sleep(delay)
    os.system('cls')
    print("     o")
    time.sleep(delay)
    os.system('cls')
    print("    o")
    time.sleep(delay)
    os.system('cls')
    print("   o")
    time.sleep(delay)
    os.system('cls')
    print("  o")
    time.sleep(delay)
    os.system('cls')
    print(" o")
    time.sleep(delay)
    os.system('cls')
    print("o")

input('Press ENTER to exit')
